### ISSUE TITLE
 Unauthorized access (Spaceship::TunesClient::ITunesConnectError) 1.0.0 beta3

### ISSUE THREAD

**Issue by The-Guru** [fastlane/deliver#349]
Hi Felix,

It seems there is another issue with deliver/spaceship. I have done a test uploading plenty of screenshots in several languages and when appearing the message "Saving changes" in the console I've got this error:

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:275:in `update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/upload_screenshots.rb:43:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/runner.rb:53:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/runner.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'
```

I'm using a Agent account for iTunes Connect so.. I should have access to update the app.
Maybe the token of the login has expired before committing the changes?

Update: It seems that even getting the Unauthorized access error the metadata and screenshots has been uploaded!. Also I'm using Xcode 6.4

Thanks.
Best,

Óscar

**Comment by The-Guru** [comment]
Update: It seems that even getting the Unauthorized access error the metadata and screenshots has been uploaded!.

**Comment by DeadCounter** [comment]
I had the same error. Then after logging in and out of iTunes Connect, the new screenshots had appeared after all - just like you mention in your update.

**Comment by bkrijgsman** [comment]
I have the same error, logging out in ITuesConnect doesn't fix this issue.

I also got another error since i updated to 1.0.0.beta3:
 `gem_path': undefined method `gem_dir' for nil:NilClass (NoMethodError)

Anybody an idea? I use ruby 2.0.0p643 2015-02-25

**Comment by KrauseFx** [comment]
@DeadCounter @bkrijgsman what kind of account do you have? Also agent?

**Comment by bkrijgsman** [comment]
Admin, Legal is the account. I will try some other account (could that be the problem?)

**Comment by KrauseFx** [comment]
@bkrijgsman It's really hard to tell. It's working fine for me and many other users, so there has to be something different on your setup.

**Comment by bkrijgsman** [comment]
Thank you for your quick response!

I tried it with an "technical" and an "admin" account, resulting in the same error. Are there any other test I can do?

**Comment by DeadCounter** [comment]
@KrauseFx I have a Technical account.

**Comment by The-Guru** [comment]
@KrauseFx Do you recommend uninstall deliver and reinstall it again? maybe is something broken when updating it.

**Comment by bkrijgsman** [comment]
I have maybe found the solution (for the gem path). I uninstalled the old version of (deliver 0.13.5), because it wans't using the correct version.

I installed deliver 0.13.5 and deliver 1.0.0.beta3 and manually selected the correct version (1.0.0.beta). I'm not getting this bug anymore, currently having (Could not find a version to edit for app 'f') another bug, but i think this is in something what happens in our own system.

**Comment by KrauseFx** [comment]
I just pushed [deliver 1.0.0](https://github.com/KrauseFx/deliver/releases/tag/1.0.0) and [fastlane 1.30.0](https://github.com/KrauseFx/fastlane/releases/tag/1.30.0). Please update using `sudo gem update fastlane` and let me know if everything works for you.
Also, make sure to follow the new [Migration Guide to 1.0](https://github.com/KrauseFx/deliver/blob/master/MigrationGuide.md).

It might not solve your issue, but please update anyway and let me know if it helps.

**Comment by eax32** [comment]
I have same error. And also screenshots have been mixed (between locales). Locale - ru and en-US.
Version 1.1.3

**Comment by kostiakoval** [comment]
get similar problem. 
```
/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/spaceship-0.11.0/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/spaceship-0.11.0/lib/spaceship/tunes/tunes_client.rb:275:in `update_app_version!'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/spaceship-0.11.0/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/deliver-1.1.3/lib/deliver/upload_screenshots.rb:43:in `upload'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/deliver-1.1.3/lib/deliver/runner.rb:53:in `upload_metadata'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/deliver-1.1.3/lib/deliver/runner.rb:20:in `run'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/deliver-1.1.3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/deliver-1.1.3/lib/deliver/commands_generator.rb:84:in `run'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/deliver-1.1.3/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/konstantin/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/deliver-1.1.3/bin/deliver:5:in `<top (required)>'
	from /Users/konstantin/.rvm/gems/ruby-2.1.1/bin/deliver:23:in `load'
	from /Users/konstantin/.rvm/gems/ruby-2.1.1/bin/deliver:23:in `<main>'
	from /Users/konstantin/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/konstantin/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```
using latest version of fastlane `1.30.2`
Even thou I see this error, the screenshots were uploaded to the iTunes Connect.
Also I did't provided some information for the metadata (leave .txt) files empty, ,maybe this is the case for that issue

**Comment by kmikael** [comment]
II'm using a fresh install of `deliver 1.1.3` and a brand new `Deliverfile` initialized with `deliver init` and I get the same error just after uploading the screenshots… Here's the stack trace:

``
…
[16:42:20]: Saving changes
/usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/spaceship-0.11.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/spaceship-0.11.1/lib/spaceship/tunes/tunes_client.rb:275:in `update_app_version!'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/spaceship-0.11.1/lib/spaceship/tunes/app_version.rb:265:in `save!'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/deliver-1.1.3/lib/deliver/upload_screenshots.rb:43:in `upload'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/deliver-1.1.3/lib/deliver/runner.rb:53:in `upload_metadata'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/deliver-1.1.3/lib/deliver/runner.rb:20:in `run'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/deliver-1.1.3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/deliver-1.1.3/lib/deliver/commands_generator.rb:84:in `run'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/deliver-1.1.3/lib/deliver/commands_generator.rb:12:in `start'
    from /usr/local/var/rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/deliver-1.1.3/bin/deliver:5:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.0.0-p647/bin/deliver:23:in `load'
    from /usr/local/var/rbenv/versions/2.0.0-p647/bin/deliver:23:in `<main>'
```

**Comment by kmikael** [comment]
**Real time update:** When I also upload an .*ipa*, I don't get the errors. This is what it looks like in the console in this case:

```
…
[17:18:28]: Saving changes
[17:18:50]: Successfully uploaded screenshots to iTunes Connect
[17:18:55]: Uploading binary to iTunes Connect
[17:18:55]: Going to upload updated app to iTunesConnect
[17:18:55]: This might take a few minutes, please don't interrupt the script
[17:18:59]: [Transporter]: INFO: Transporter is searching for updated software components.
[17:19:07]: [Transporter]: INFO: Transporter is up-to-date.
[17:19:08]: [Transporter]: INFO: Logging configured successfully.
etc…
```

Maybe ab an option like `--skip-ipa` would be useful for when the *ipa* has already been uploaded and only the screenshots want to be uploaded/updated. We often upload the screenshots beforehand while were are fixing a few last minute bugs. SO that we can release immediately after the last few bugs have been fixed and tested. And then an option to skip the screenshots might be useful.

**Comment by KrauseFx** [comment]
@kmikael If you don't pass an ipa / screenshots, they will automatically be skipped.

**Comment by KrauseFx** [comment]
It seems like Apple is currently having timeout issues with iTunes Connect - this isn't an error of `deliver`

**Comment by kmikael** [comment]
Sorry, it must have been a coincidence than.

**Comment by ciryon** [comment]
Also having this problem.

**Comment by floskel** [comment]
Seeing this message when uploading only metadata and screenshots. It seems that the new information is uploaded and saved tho.

**Comment by dfranzi** [comment]
Been encountering this issue consistently since migrating yesterday as well. This always occurs after uploading screenshots and "Saving changes" is logged. Deliver seems to hang here for a while and then eventually bail out with the 'unauthorized_access' error.

**Comment by pieisgood** [comment]
Is there a way to ping certain apple urls to check if this is, in fact, a timeout?

**Comment by pieisgood** [comment]
Gave apple a call and they fixed the issue. Similar errors were happening within itunes connect it self.

**Comment by KrauseFx** [comment]
![4284240](https://cloud.githubusercontent.com/assets/869950/10325915/7b27d508-6c63-11e5-83b4-2e621b868efd.jpg)

> I just gave Apple a call, and they fixed it

Nice, I love that in combination with your picture! :+1:

**Comment by dral3x** [comment]
It seams a timeout issue in iTC. Normally I upload 16 screenshots per app. If I try to upload 4, the "Save changes" works.

I agree that it's an iTC issue but can we introduce a workaround? Maybe upload and save just 4 screenshots and then iterate until all are published? Could this work?

**Comment by lacostej** [comment]
I made a per language upload, per Felix request, but that doesn't fix it at my place. Investigating further...

**Comment by dral3x** [comment]
I had just one language but still, 16 screenshots in a row it's too much. If you could try to split also per device would be great. Thanks @lacostej

**Comment by lacostej** [comment]
I've been playing with that for a while and it still doesn't work.

I also experimented with increasing the timeout, reducing the number of request, etc. I still don't have a stable build. See https://github.com/lacostej/spaceship/commits/workaround_timeout

Note that the faraday retry mechanism won't kick in for non idempotent methods (thus POSTs). That's why I increased it to 5 min instead.

It still won't work reliably.

Types of errors I keep getting:

`````
/Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite': Broken pipe (Errno::EPIPE)
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:211:in `write0'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:185:in `block in write'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:202:in `writing'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:184:in `write'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:187:in `send_request_with_body'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:120:in `exec'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/lacostej/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
`````

How do you want to work-around something like that...

I hit similar failures in the browser so my current conclusion is that my time would be better served fixing ITC instead...

I give up for today

**Comment by dfranzi** [comment]
Is this a new limitation on connection limits from the iTC side? Does the deliver process currently track which steps have succeeded? It might be possible to build in a generic retry/backoff policy to handle timeouts or disconnections if this is now going to be expected behaviour when communicating with iTC.

**Comment by lacostej** [comment]
E.g. of last error I got:
````
[23:48:18]: Saving changes
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/spaceship-0.11.2/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/spaceship-0.11.2/lib/spaceship/tunes/tunes_client.rb:278:in `update_app_version!'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/spaceship-0.11.2/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/deliver-1.3.1/lib/deliver/upload_screenshots.rb:51:in `block in upload'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/deliver-1.3.1/lib/deliver/upload_screenshots.rb:27:in `each'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/deliver-1.3.1/lib/deliver/upload_screenshots.rb:27:in `upload'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/deliver-1.3.1/lib/deliver/runner.rb:53:in `upload_metadata'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/deliver-1.3.1/lib/deliver/runner.rb:20:in `run'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/deliver-1.3.1/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
`````

This after uploading about 60 screenshots, and thus about 12 previous saves of the app_version in the previous 12 min. No idea why this one fails. This isn' t a timeout. We're getting disconnected.

Now the client should become smarter. That's for sure. Not sure what the server must do upon app_version save.

**Comment by dfranzi** [comment]
Has anyone found a workaround in the meantime? I've tried skipping various steps of the upload, but still have only managed to have deliver complete successfully once out of forty or so tries.

**Comment by lacostej** [comment]
I have been running various tests today, with a modified version of deliver+spaceship. It looks a bit better but I don't know if because of sheer luck, Apple server improvements or the code changes.

I need to set up concurrent projects uploads to compare both versions.

**Comment by RomainBoulay** [comment]
I have the same problem and could not find a solution yet. @KrauseFx is there a fix in development?
Cheers.

**Comment by txaidw** [comment]
I think I have the same problem here. Even tried to upload one single screenshot. Still not working.
```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Spaceship::TunesClient::ITunesConnectError
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.1/lib/spaceship/tunes/tunes_client.rb:278:in `update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.1/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/lib/deliver/upload_metadata.rb:88:in `verify_available_languages!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/lib/deliver/upload_metadata.rb:22:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/lib/deliver/runner.rb:52:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/lib/deliver/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.2/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

**Comment by peter542** [comment]
I have the same “Unauthorized access” error after uploading 240 screenshots. It takes more than 1 hour to upload. Then after saving changes the error occurs. The screenshots stays the same in ITC.

**Comment by benoitsan** [comment]
Hi Felix,

I had the same issue today when I uploaded 390 screenshots, it generated an error when saving changes step occurred **but the screenshots were correctly uploaded to iTunes Connect and are visible in the portal**.

`$ deliver --skip_metadata`

1. Screenshot upload.
2. Upload complete, saving changes step stops with this error /lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)

**Comment by lacostej** [comment]
I've worked a bit on a tool to reproduce all these connection issues.  And I have some findings.

For example, I've found that when we get the Unautorized error, it seems that we in fact get the answer from a different apple server (different x-apple-application-instance).

Looking at Charles intercepted info and the browser one, we're not sending the exact same cookies, etc. I'll try to see if I can rewrite the whole faraday integation and see if that helps.

If that doesn't work, an alternative would be to force re-logging when the server has changed (e.g. if restarted).

**Comment by txaidw** [comment]
Still getting the errors here. Anything new?

**Comment by lacostej** [comment]
@txaidw working on it. See the above referenced issue fastlane/spaceship#150

**Comment by KrauseFx** [comment]
Please update to https://github.com/fastlane/deliver/releases/tag/1.5.2 and let me know if that works for you :+1:

**Comment by rewislam** [comment]
Still getting "Unauthorized access", using v1.6.4 of deliver.

**Comment by Wojcik** [comment]
Same with 1.6.6

**Comment by DeadCounter** [comment]
Same for me with 1.6.6 - updated to 1.7.0, still no good - but nice job on the improved Preview file :)

**Comment by jonas-andersson-stratsys** [comment]
Have the same error. I have two different apps. One works fine uploading meta_data and screenshots, the other one gets this error.
